name: Testes - Principal

on:
  pull_request:
    branches: [principal]

jobs:
  testes-unitarios:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '24'
    - run: yarn install
    - name: Executar testes com cobertura
      run: yarn testes --ci --json --testLocationInResults --outputFile=report.json
      continue-on-error: true
    - run: echo "${{ github.event.number }}" > pr-number.txt
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: relatorio-testes
        path: |
          report.json
          pr-number.txt
        retention-days: 1
